### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by Juank628** [Juank628/Rails-recipe#12]
Link to the project repo:
https://github.com/Juank628/Rails-recipe

We are 2 members

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- The points should be written in the format **1pt** where 1 is the time and 'pt' symbolizes the unit of measurement.
![image](https://user-images.githubusercontent.com/27709832/232546776-043fbea8-0b4b-43d4-b458-7878a12be1b5.png)
- Kindly provide descriptions for all cards in the Kanban board.
![image](https://user-images.githubusercontent.com/27709832/232548729-7245733c-96df-4049-bc84-50acea6bb8f9.png)
- Kindly move the notes you've added into description boxes.
![image](https://user-images.githubusercontent.com/27709832/232549582-f8a026bc-b06d-4173-836c-dc80e3cf8914.png)
- Kindly add a card for the handling of N+1 queries as stated in the project requirement.
![image](https://user-images.githubusercontent.com/27709832/232550037-fd8e6026-d842-4a87-b890-27af61b07245.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by addod19** [comment]
### Hi @Juank628 and @PrangonGhose, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 
- [ ] Nice job addressing some of the comments made by the previous reviewer :man_technologist: 


 ## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we assign points [pt] as stated earlier to our `N+1 queries`
![Screenshot from 2023-04-17 20-13-12](https://user-images.githubusercontent.com/46388113/232587953-8b57baf1-9d4c-4ca5-aff1-0e20e0b30e9a.png)


## Optional suggestions
- [ ] It would be nice if we provide the correct link to the kanban board, it's currently like [this](https://github.com/Juank628/Rails-recipe) instead of [this](https://github.com/users/Juank628/projects/2/views/1)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vickymarz** [comment]
Hi @brytebee, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Required changes implemented ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
